function fileCleanup2 = createTempClassFile(name)
%CREATETEMPCLASSFILE creates temporary class file to be used with recoverObject 
% aids in recovery of lost custom classes by creating temp class that
% custom class objects can be loaded with
%
%INPUTS:
% - name = name of the class to be used
%OUTPUTS:
% - fileCleanup2 = onCleanup object that will delete the file when cleared
%
% See also ONCLEANUP and RECOVEROBJECT

arguments
    name char
end

% create a new matlab file to be used to initiate the class
fileName = strcat(name,'.m');
fid = fopen(fileName,'w');
fileCleanup1 = onCleanup(@() closeFile(fid));
fileCleanup2 = onCleanup(@() delete(fileName));

% write in the necassary class
codeString = classCodeString(name);
fprintf(fid,'%s\n',codeString{:});
fclose(fid);

    function closeFile(fid)
        % to be handed to file cleanup 1
        if any(fid == fopen('all'))
            close(fid)
        end
    end

    function code = classCodeString(className)
        % code for 
        code = [{['classdef ' className                                                ]} ...
                { '    %TEMP this file should be deleted if found only to be used with' } ...
                { '    % recoverObject function that recovers lost custom classes '     } ...
                { '    '                                                                } ...
                { '    properties'                                                      } ...
                { '        structure'                                                   } ...
                { '    end'                                                             } ...
                { '    '                                                                } ...
                { '    methods'                                                         } ...
                {['        function obj = ' className '(loadedStructure)'              ]} ...
                { '            obj.structure = loadedStructure;'                        } ...
                { '        end'                                                         } ...
                { '    end'                                                             } ...
                { '    '                                                                } ...
                { '    methods (Static)'                                                } ...
                { '        function obj = loadobj(objStruct)'                           } ...
                {['            obj = ' className '(objStruct);'                        ]} ...
                { '        end'                                                         } ...
                { '    end  '                                                           } ...
                { 'end'                                                                 }];
    end
end